# Fix all console-script shebangs in the venv that point to the wrong drive.
#
# After moving a venv from one drive/path to another, every pip-generated
# .exe / console_script wrapper keeps its original shebang pointing to the
# old Python location. The fix is to rewrite those bytes in-place to
# reference the current venv's Python.
#
# Usage: powershell -File scripts/fix_venv_shebangs.ps1

$ErrorActionPreference = "Stop"

$BackendRoot = (Resolve-Path "$PSScriptRoot\..\backend").Path
$VenvScripts = Join-Path $BackendRoot "venv\Scripts"
$TargetPython = Join-Path $VenvScripts "python.exe"

if (-not (Test-Path $TargetPython)) {
    throw "Target python not found: $TargetPython"
}

# The pattern we want to replace. Console_script wrappers embed the
# shebang as ASCII bytes. Match any of:
#   - D:\eclassroom_day2\...python.exe
#   - F:\eclassroom_day2\...python.exe  (already correct, no-op)
#   - Any drive letter + eclassroom_day2 + ... + python.exe
$OldPattern = '[A-Z]:\\eclassroom_day2\\backend\\venv\\Scripts\\python\.exe'
$Replacement = $TargetPython

Write-Host "Target python: $TargetPython" -ForegroundColor Cyan
Write-Host "Scanning *.exe in $VenvScripts ..." -ForegroundColor Cyan

$fixed = 0
$skipped = 0
$errors = 0

Get-ChildItem -Path $VenvScripts -Filter "*.exe" | ForEach-Object {
    $path = $_.FullName
    try {
        $bytes = [System.IO.File]::ReadAllBytes($path)
        $text = [System.Text.Encoding]::ASCII.GetString($bytes)

        if ($text -notmatch $OldPattern) {
            $skipped++
            return
        }

        # Determine the byte length of the old path so we can replace
        # in-place (preserving the original byte width, important if
        # the new path happens to be a different length — we pad with
        # NULs to keep the binary layout consistent, though the launcher
        # only reads until the first NUL).
        $matches = [regex]::Matches($text, $OldPattern)
        if ($matches.Count -eq 0) {
            $skipped++
            return
        }

        $firstMatch = $matches[0]
        $oldLiteral = $firstMatch.Value
        $oldByteLen = [System.Text.Encoding]::ASCII.GetByteCount($oldLiteral)
        $newByteLen = [System.Text.Encoding]::ASCII.GetByteCount($Replacement)

        if ($newByteLen -le $oldByteLen) {
            # Simple: replace bytes, pad remainder with NULs
            $newBytes = [System.Text.Encoding]::ASCII.GetBytes($Replacement)
            $padLen = $oldByteLen - $newByteLen
            $padded = $newBytes + (0..($padLen - 1) | ForEach-Object { [byte]0 })
            $start = $firstMatch.Index
            for ($i = 0; $i -lt $oldByteLen; $i++) {
                $bytes[$start + $i] = $padded[$i]
            }
        } else {
            # New path is longer than old. Rare, but handle it by
            # writing the new path at the start of the binary and
            # leaving a length-warning in the console. Console_script
            # wrappers generated by pip are typically >= 80KB so we
            # almost always have room.
            Write-Warning "$($_.Name): new path is longer than old ($newByteLen > $oldByteLen). Skipping (use `pip install --force-reinstall <pkg>` to regenerate)."
            $skipped++
            return
        }

        [System.IO.File]::WriteAllBytes($path, $bytes)
        Write-Host "  fixed $($_.Name)" -ForegroundColor Green
        $fixed++
    } catch {
        Write-Warning "  error fixing $($_.Name): $_"
        $errors++
    }
}

Write-Host ""
Write-Host "Fixed: $fixed, Skipped: $skipped, Errors: $errors" -ForegroundColor Cyan
